/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   etools-upload-multi.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {LitElement} from 'lit-element';

/**
 * `etools-upload-multi` Description
 */
declare class EtoolsUploadMulti extends LitElement {
  uploadBtnLabel: string|null|undefined;
  rawFiles: any[]|null|undefined;
  _filenames: any[]|null|undefined;
  _filesSelected(e: any): void;
  _extractFilenames(files: any): any;
  _handleUpload(files: any): void;
  _clearDisplayOfUploadedFiles(): void;
  _uploadAllFilesSequentially(files: any, upload: any, set: any): any;
  _shouldDisableUploadBtn(readonly: any, uploadInProgress: any): any;
  _thereAreFilesSelected(_filenames: any): any;
  _cancelUpload(): void;
  resetRawFiles(): void;
}

declare global {

  interface HTMLElementTagNameMap {
    "etools-upload-multi": EtoolsUploadMulti;
  }
}
