/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   etools-upload.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {PolymerElement, html} from '@polymer/polymer';

import {CommonMixin} from './common-mixin.js';

import {RequestHelper} from './request-helper.js';

/**
 * `etools-upload`
 * Use to upload files
 */
declare class EtoolsUpload {
  uploadBtnLabel: string | null | undefined;
  alwaysFloatLabel: boolean | null | undefined;
  fileUrl: string | null | undefined;
  _filename: string | null | undefined;
  rawFile: object | null | undefined;
  showDeleteBtn: boolean | null | undefined;
  errorMessage: string | null | undefined;
  originalErrorMessage: string | null | undefined;
  serverErrorMsg: string | null | undefined;
  success: boolean | null | undefined;
  fail: boolean | null | undefined;
  showChange: boolean | null | undefined;
  allowMultilineFilename: boolean | null | undefined;
  invalid: boolean | undefined;
  connectedCallback(): void;
  _thereIsAFileSelectedOrSaved(_filename: any): any;
  _fileSelected(e: any): void;
  _fireChangeFileEventIfApplicable(): void;
  _handleUpload(): void;
  setInvalid(invalid: any, errMsg: any): void;
  resetValidations(): void;
  resetStatus(): void;
  _fileUrlChanged(fileUrl: any): void;
  getFilenameFromURL(url: any): any;
  _showDownloadBtn(fileUrl: any): any;
  _showChange(readonly: any, _filename: any, uploadInProgress: any, showChange: any): any;
  _showDeleteBtn(readonly: any, _filename: any, showDeleteBtn: any, uploadInProgress: any): any;
  _cancelUpload(): void;
  _deleteFile(e: any): void;
  resetRawFile(): void;
  _downloadFile(e: any): void;
  validate(): any;
  autoValidateHandler(): void;
}

declare global {

  interface HTMLElementTagNameMap {
    "etools-upload": EtoolsUpload;
  }
}
